### ISSUE TITLE
Font size not applied properly in composite diagram

### ISSUE THREAD

**Issue by cchalmers** [diagrams/diagrams-svg#66]
Applying `fontSize` to a composite diagram doesn't render properly:

```haskell
rightSize = square 3 <> text "hi" # fontSizeL 2
wrongSize = (square 3 <> text "hi") # fontSizeL 2
```

Inspecting the SVG output shows the correct size is applied in an outer group but the `Recommend`ed size is used in an inner group and that's what gets shown. I suspect this is from the recent changes to `Measure`. It doesn't happen in the `rasterific` or `pgf` backends.

**Comment by cchalmers** [comment]
On a related issue, certain attributes are being output several times even though they're identical. Here's the gradient example from the tutorial: http://lpaste.net/129623. Each gradient is defined an applied 3 times even though they're identical.

I think if we accumulate the style in the state and only apply the style when it's used, like the other backends, both these issues should be fixed.

**Comment by jeffreyrosenbluth** [comment]
The reason that the SVG backend doesn't accumulate styles using the state stack is probably a bit of a historical accident. When i switched to an `RTree` instead of a list of primitives one of the first things i did was to port the svg backend. Hence the `RTree` based backend probably inherited these redundancies from the list based backend. This was before byorgey designed the state stack to convert the cairo backend. It's probably worth looking into @cchalmers suggestion.
