### ISSUE TITLE
Gradient is not applied to text

### ISSUE THREAD

**Issue by alexDarcy** [diagrams/diagrams-svg#98]
Using a linear gradient to fill some text does not work. 

This is specific for the SVG backend as it works for the rasterific backend. Here is a minimal working example:

    {-# LANGUAGE NoMonomorphismRestriction #-}
    
    import Diagrams.Prelude
    import Diagrams.Backend.SVG.CmdLine
    
    stops = mkStops [(gray, 0, 1), (white, 0.5, 1), (purple, 1, 1)]
    gradient = mkLinearGradient stops ((-0.5) ^& 0) (0.5 ^& 0) GradPad
    
    text1 :: Diagram B 
    text1 = rect 20 8 <> text "Hello" # fontSize (local 4) # fillTexture  gradient
    
    main = mainWith text1

Replacing `GradPad` with `GradRepeat` shows a gradient applied to the text though.

**Comment by cchalmers** [comment]
This should be fixed now. We keep track of the transforms for gradients and text separately but SVG applies the text transform to the gradient transform so it was getting double applied in your example. The gradient was still there, it was just translated to the right so you could only see the grey.

This was actually quite tricky to solve because the SVG canvas is upside down.
